### ISSUE TITLE
Automatic domain renewal failed Admin mail

### ISSUE THREAD

**Issue by PhiGi87** [centralnicgroup-opensource/rtldev-middleware-whmcs#256]
**Describe the bug**
We always get the message "Automatic domain renewal failed" by email when a customer pays their bill. But the domain was renewed. This is a bit irritating and maybe should be fixed.

**To Reproduce**
1. Pay an invoice for an automatic domain renewal.

**Expected behavior**
An admin email that the automatic domain renewal was successfully completed.

**Screenshots**

**Context (please complete the following information):**
 - WHMCS 8.7.2
 - PHP 7.4
 - ISPAPI Registrar Module Version 19.0.4
 - Domain Registrar is Hexonet

**Comment by PhiGi87** [comment]
It seems independent. I've looked and so far found all the tlds I have (com, de, net, shop)


Am 20. Juli 2023, 15:41, um 15:41, Kai Schwarz ***@***.***> schrieb:
>Thanks @PhiGi87 I'll check that. What's the TLD (or independent of
>that)?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/issues/256#issuecomment-1643949406
>You are receiving this because you were mentioned.
>
>Message ID:
>***@***.***>


_________________________________________________________________
Hol' auch Du dir deine kostenlose Email auf www.Uelzen.email

**Comment by PhiGi87** [comment]
I took a closer look again. It's obviously TLD independent!

**Comment by KaiSchwarz-cnic** [comment]
@PhiGi87 I checked anything related to renewals for the HEXONET Integration:

**the AfterRegistrarRenewal hook**

=> nothing related identified

**the registrar module function `ispapi_RenewDomain`**

Here, Domain Renewals and Restores are covered. The function has to return either

```
[
    "success" => true
]
````

or

```
[
    "error" => "Some Error happened (just an example)"
]
```

I validated this against the [Sample Registrar Module, Lines 528ff](https://github.com/WHMCS/sample-registrar-module/blob/master/modules/registrars/registrarmodule/registrarmodule.php#L528-L540).

That's the case and by this, I don't see an error in our source code.

Further more, we are not sending those emails out - WHMCS is doing that. We return just the renewal result to WHMCS. In case a renewal would have failed, it would be dangling around in the Module Queue for retry. As I understood you, this isn't the case.
So, conclusion: I don't consider the module's RenewDomain function as the root cause of this.

Do you have maybe the CNIC Migrator Addon in use? Activated and Configured?
I am just asking because that Addon is plugging into the renewal process right after invoice payment.
When confirmed, I'll have an eye on that one too.

Kind Regards

**Comment by PhiGi87** [comment]
Hello, thank you for checking. I knew that WHMCS sends the admin email, but there must be some trigger somewhere that tells WHMCS to notify me of a "failure."

As you correctly noticed, it doesn't end up in the Module Queue. On the contrary, in the system activity log, I find the entry "Domain Renewed Successfully."

I'm not using the CNIC Migrator Addon. I haven't quite understood what advantage it brings to me yet.

**Comment by KaiSchwarz-cnic** [comment]
@PhiGi87 ah, that makes it more clear. 

Initially, you mentioned:

> We always get the message "Automatic domain renewal failed" by email

... and in your last comment:

> in the system activity log, I find the entry "Domain Renewed Successfully."

I just had an eye on the 1st topic on Friday. We have a logging review in work which means that anything we log using CentralNic Reseller or HEXONET will follow a generic syntax, will be considering the client as related party in case the action got triggered by him, etc. I'll check this there and will ensure it will be patched by that review. Thanks for addressing.
We expect that this review improves the reseller experience.

**Comment by KaiSchwarz-cnic** [comment]
v19.0.10 is out.
