### ISSUE TITLE
Missing attribute required for transfer of premium domain

### ISSUE THREAD

**Issue by typohub** [centralnicgroup-opensource/rtldev-middleware-whmcs#257]
**Describe the bug**
When trying to transfer in a .ICU via WHMCS we get the following Error

**To Reproduce**
1. Go to <whcmsinstalldir>/modulequeue.php
2. Click on retry
3. See error ' Retry Response: Missing required attribute; CLASS=PREMIUM_ICU_USD:6:6 required for Transfer of Premium Domain"

**Expected behavior**
Transfer of Domain Name.

**Test of command via hexonet api:**
command = TransferDomain
domain = <domain>
action = Request
auth = <auth code>
class = PREMIUM_ICU_USD:6:6
EOF

returns different error

{
    "DESCRIPTION": "Invalid attribute value; could not get domain transfer fee refundable",
    "CODE": "541",
    "QUEUETIME": "0",
    "RUNTIME": "0.132"
}

**Comment by KaiSchwarz-cnic** [comment]
Good Day @typohub !

Identifying the root cause of all this is hard without knowing the exact domain name. Somehow this sounds like a so-called variable free premium domain. Usually for premium domains, only the class name is required which is different to this example here. usually we add something like `class = PREMIUM_ICU_USD` only. This case as mentioned is probably a rare case and we need the domain name for digging deeper.

Please open a support ticket by sending an email to our technical support - find the contact data here: https://www.hexonet.net/contact.

Thanks so much!
