### ISSUE TITLE
why I have to sync two times  pricing ?

### ISSUE THREAD

**Issue by jsjcjsjc** [centralnicgroup-opensource/rtldev-middleware-whmcs#258]
WHMCS 8.1.3
rtldev-middleware-whmcs v20.0.1
After testing, I find my first pricing sync always failed, please check the log in the pictures below
Thanks
[![123456.jpg](https://7up.pics/images/2023/08/13/123456.jpg)](https://7up.pics/image/1RYlC)

**Comment by jsjcjsjc** [comment]
another question how to sync all TLD into WHMCS ? It looks in this page, my edge always stop working...
[![image.png](https://7up.pics/images/2023/08/13/image.png)](https://7up.pics/image/1RCAR)

**Comment by jsjcjsjc** [comment]
hello ?

**Comment by KaiSchwarz-cnic** [comment]
@jsjcjsjc Good Day!

Sorry for the delay, I had been ooo.

I remember that we discussed the 1st topic already in the past with you (Errors of GetZoneInfo). If I recall correctly, those can be ignored as they are about TLDs that are either not compatible to the WHMCS pricing structure or not activated on your account.
The data GetZoneInfo returns is getting cached and that's why you don't see those errors occuring again when retrying.
It is probably confusing having all those entries in the Module Log, but that's how it works ... any API Call has to appear in the module log as it covers the entire API Communication Logs.

The 2nd issue you're reporting isn't something we can help with. We only return data to WHMCS. When clicking on "Import", WHMCS itself is doing the import. If there's something not working correctly (like that popup you noticed), you'll have to report this to WHMCS via support ticket at https://whmcs.com.

Hope that helps!
