### ISSUE TITLE
why I can't use "CNIC Domain Search"

### ISSUE THREAD

**Issue by jsjcjsjc** [centralnicgroup-opensource/rtldev-middleware-whmcs#262]
WHMCS 8.13
RRPproxy[v19.1.3]

Hi
After installing and active CNIC Domain Search in WHMCS, I try to use the link below to test "CNIC Domain Search", but there is nothing.
https://www.cloudwings.net/mydomainsearch.php?action=register&searchTerm=test.com

could you please help me with it ?
Thanks in advance

![image.png](https://7up.pics/images/2023/08/23/image.png)

**Comment by AsifNawaz-cnic** [comment]
Hello,

I understand the issue you're facing and have reviewed it on our end. It appears that the system URL you're using is "https://cloudwings.net," while you're attempting to access our search engine from "https://www.cloudwings.net." Due to security headers in place, Cross-Origin Resource Sharing (CORS) is being prevented, leading to the unexpected behavior of the Domain search addon.

To resolve this, you have a few options:

1. Update your system URL: Include "www" in the system URL if your intention is to use "www.cloudwings.net" instead of just "cloudwings.net."

2. Redirect requests: You can set up a redirection for all requests coming from the "www.cloudwings.net" subdomain to "cloudwings.net" using htaccess configuration.

3. Use the domain search addon directly: You can also utilize our domain search addon without the "www" subdomain. Here's the link: [https://cloudwings.net/mydomainsearch.php?action=register&searchTerm=test.com](https://cloudwings.net/mydomainsearch.php?action=register&searchTerm=test.com)

Feel free to choose the option that best suits your needs. If you have any further questions or require assistance, please let us know.
