### ISSUE TITLE
is there stable version tested with fewer bugs ?

### ISSUE THREAD

**Issue by jsjcjsjc** [centralnicgroup-opensource/rtldev-middleware-whmcs#266]
Hi
is there stable version tested with fewer bugs ?
thanks

**Comment by KaiSchwarz-cnic** [comment]
Hi @jsjcjsjc 

we are always testing new releases. Still, as of complexity of different system setups on reseller-side, it is sometimes more difficult (PHP8 vs PHP7, MySQL vs MariaDB, Ubuntu vs CentOS vs ..., ...).

If there's something not working that you want to share - please address it. Otherwise it isn't worth opening such a github issue (even though I understand a reseller's frustration in case something breaks).

We are always happy to help, but without further input ...

Thanks &
Kind Regards

**Comment by jsjcjsjc** [comment]
Hello
I think there are some misunderstandings. Generally, software has beta, RC, stable and other versions. I found that the default version of RRPproxy updates very frequently, and it is unlikely that every version has been fully tested, so I wonder if there is a version that has been fully functional testing ?
thanks

**Comment by DennisSkov** [comment]
@jsjcjsjc most of the releases you find here are bug fixes. IIRC, @KaiSchwarz-cnic fixes bugs as soon as he finds them (which is why you often see releases with basically no changelog). Fixing bugs rarely introduces another bug.
Big releases (i.e 19.0.0, 20.0.0, 21.0.0 etc) _could_ introduce things that would break stuff but it's my understanding that Kai generally does a really good job of testing before doing a new release.

If you want the most stable release, wait for for patches (MAJOR.MINOR.PATCH).

We usually upgrade whenever we see a new release and I don't remember when we last had an issue that was caused by the module tbh.

**Comment by KaiSchwarz-cnic** [comment]
@jsjcjsjc ah, understood. Sorry that I got you entirely wrong then.

There's neither any other release channel available, nor is it planned.

We just recommend watching the new releases and to only upgrade in case there's something broken and patched by that release or if there's a new feature of interest added. It is not useful to upgrade each time. We are aware of that especially the upgrade process is taking too much time for the amount of releases going out. We have an upgrade wizard in planning that will be helping in future. We recommend at least upgrading on each major release - so X.0.0. Then also please ensure to read the release notes to identify the breaking changes and if there's something special to consider (a manual upgrade step like with the templates/child themes in v20.0.0 or v21.0.0).

We were also testing with a quaterly release, but there were too many changes recently which were about refactoring, aligning and improving the CNR and HX Integrations plus rewriting in direction of new possibilities of WHMCS 8. We might come back to that approach when we see us releasing less often.

Thanks for the clarification @jsjcjsjc and @DennisSkov for supporting as well! Very much appreciated :smiley:
