### ISSUE TITLE
Hexonet TLD Import & Pricing Sync not working

### ISSUE THREAD

**Issue by Showfom** [centralnicgroup-opensource/rtldev-middleware-whmcs#279]
**Describe the bug**

**To Reproduce**
1. Go to '/utilities/tools/tldsync/import'
2. Click on 'Hexonet logo'
3. Wait

```
SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'utf8mb4_general_ci' is not valid for CHARACTER SET 'utf8mb3' (SQL: create table `ispapi_tblrelations` (`relation_subclass` varchar(255) not null, `relation_value` varchar(255) not null, `relation_category` varchar(255) not null, `relation_subcategory` varchar(255) not null, `relation_type` varchar(255) not null, `relation_period` tinyint null) default character set utf8 collate 'utf8mb4_general_ci')
```

**Context (please complete the following information):**
 - WHMCS Version [e.g. 7.6] 8.10.1
 - Server OS: [e.g. Ubuntu 18.04, iOS8.1] Debian 12
 - PHP Version [e.g. 7.2.12] 8.1.29
 - Registrar: [e.g. CNR, HX, IBS, TPP *] HX
 - Module Version: [WHMCS built-in, or version number] 23.8.2

> NOTE: HX = HEXONET, CNR = CentralNic Reseller, IBS = internet.bs, TPP = TPP Wholesale

**Comment by KaiSchwarz-cnic** [comment]
We had been in touch with WHMCS Support in the past as we noticed such issues on our customer's systems, but usually conflicting with `latin_swedish_ci` (or similar). We asked about the right way of creating DB Tables via the DB Class, so which charset and collation to define and use. We did not receive a clear response, just that charset utf8 is fine (what they use as well). That's right, install.sql of WHMCS is showing that as well. Still, it looks like we're conflicting with the collation of existing DB Tables when creating a new one as the collation is either completely different and by that, we even notice that customers have an issue with their DB in general (they drive with `latin_swedish_ci` instead of utf8) and your case is even different. I decided now to entirely disable any character set / collation setting when creating tables on our end. Hopefully this finally helps.

v23.8.3 will be released asap.
